### ISSUE TITLE
[Feature Request] `Dockerfile` / `environment.yml` for better reproducibility

### ISSUE THREAD

**Issue by SauravMaheshkar** [DeepGraphLearning/NBFNet#1]
Congratulations to the authors for NeurIPS'21, looking forward to your talk during LoGaG

---

While installing the project on VMs **and** local systems, I've been running into multiple issues getting the correct package versions installed. Be it CUDA errors while installing `torch-scatter` and `torchdrug` or simply `pybind11` issues. Having a Dockerfile would help out with preventing such errors and make reproducibility + experimentation easier.

I think it'd be easier and better for there to be a Docker image for `torchdrug` itself and then the image for NBFNet would just use that as the base image. More than happy to take this up.

This way one could also use the nvidia container toolkit for running experiments across multiple GPUs/nodes easily.

**Comment by KiddoZhu** [comment]
Hi! That's a great suggestion! We can add a `environment.yml` for NBFNet soon. For the Docker image, we are not so familiar with the steps, and will probably take some time to figure it out. Like you said, a docker image is easy to launch experiments across multiple nodes, so we will definitely add one for `torchdrug`.

**Comment by naman308** [comment]
hi i am not able to run this project and even tried running on google colab for training 1 epoch with batch 8 because it is not running with original configuration on google colab but still it took so much time and google colab disconnected its service.
if u don't mind  can u share a video of executing this project once and also don't forget to add results  after executing that command in video. it is kind request to u please its urgent.  please

**Comment by SauravMaheshkar** [comment]
I just built this [**`Dockerfile`**](https://github.com/SauravMaheshkar/NBFNet/blob/main/Dockerfile) over on my [fork](https://github.com/SauravMaheshkar/NBFNet) of the repository.

```dockerfile
# syntax=docker/dockerfile:1.2
# To build the image use :-
# $ DOCKER_BUILDKIT=1 docker build .
FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime

# metainformation
LABEL version="0.0.1"
LABEL maintainer="Saurav Maheshkar"

# Helpers
ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

WORKDIR /code
COPY . .

RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel
RUN pip3 install --no-cache-dir torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
RUN pip3 install --no-cache-dir torchdrug
RUN pip3 install --no-cache-dir -r requirements.txt

RUN find /opt/conda/lib/ -follow -type f -name '*.a' -delete \
    && find /opt/conda/lib/ -follow -type f -name '*.pyc' -delete \
    && find /opt/conda/lib/ -follow -type f -name '*.txt' -delete \
    && find /opt/conda/lib/ -follow -type f -name '*.mc' -delete \
    && find /opt/conda/lib/ -follow -type f -name '*.js.map' -delete \
    && find /opt/conda/lib/ -name '*.c' -delete \
    && find /opt/conda/lib/ -name '*.pxd' -delete \
    && find /opt/conda/lib/ -follow -type f -name '*.md' -delete \
    && find /opt/conda/lib/ -follow -type f -name '*.png' -delete \
    && find /opt/conda/lib/ -follow -type f -name '*.jpg' -delete \
    && find /opt/conda/lib/ -follow -type f -name '*.jpeg' -delete \
    && find /opt/conda/lib/ -name '*.pyd' -delete \
    && find /opt/conda/lib/ -name '__pycache__' | xargs rm -r

ENV PATH /opt/conda/bin:$PATH
```

Thoughts on this @KiddoZhu ?

**Comment by KiddoZhu** [comment]
Thanks for the recipe. I just learned some basics of Docker. It looks like I can't import torchdrug correctly with this Dockerfile. It says `libXrender.so` is missing. Besides, the JIT compliation used in torchdrug relies on `nvcc` so I guess we need a development version of PyTorch image. I will figure it out.

**Comment by KiddoZhu** [comment]
Here is my `Dockerfile` for torchdrug. We have to rely on the development version of PyTorch to use JIT in torchdrug (and also required by NBFNet).

```dockerfile
FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel

RUN apt-get update && \
    apt-get install -y libxrender1 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html  && \
    pip install torchdrug
```

I am not familiar with how to prune the size of the image. I feel your `find ... -delete` commands look a little bit unsafe. Have you tested that? @SauravMaheshkar

**Comment by SauravMaheshkar** [comment]
Yes I have tested that, but in my experience it doesn't contribute much towards decreasing image size. It might be better just to use multi-stage builds, maybe something like :-

```dockerfile
# Builder Image
FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel AS builder

....

# Runner Image
FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel AS runner

...
```

**Comment by SauravMaheshkar** [comment]
Any updates ? @KiddoZhu

**Comment by SauravMaheshkar** [comment]
Might I also suggest the addition of `ENV PATH /opt/conda/bin:$PATH` at the end of the Dockerfile, the PyTorch Docker Image uses conda to handle the python interpreter without it's addition the underlying libraries aren't accessible by default.
