### ISSUE TITLE
Hits@10 of RotatE is higher than original paper.

### ISSUE THREAD

**Issue by quqxui** [DeepGraphLearning/NBFNet#13]
Hi, 

I found the Hits@10 of RotatE in FB15k237 **(0.553)** is higher than original paper **(0.533)**.  And others are same.

Is this a recording error or did you improve the performance of RotatE?

**Comment by KiddoZhu** [comment]
We took the performance directly from RotatE's paper. Sorry it might be a typo in the paper.
