### ISSUE TITLE
not able to execute this code

### ISSUE THREAD

**Issue by naman308** [DeepGraphLearning/NBFNet#2]
hi i am not able to run this project and even tried running on google colab for training 1 epoch with batch 8 because it is not running with original configuration on google colab but still it took so much time and google colab disconnected its service.
if u don't mind can u share a video of executing this project once and also don't forget to add results after executing that command in video. it is kind request to u please its urgent. please

**Comment by KiddoZhu** [comment]
Hi! The original configuration is carried out on 4 V100 GPUs (32GB). For Colab cases, you need to manually reduce the batch size to half or a quarter of the original one. I guess the time of Colab is not enough for a full training, so you'd better reduce the epoch to 1 to observe some initial results.

Could you elaborate your problem a little bit more?

**Comment by naman308** [comment]
sorry but i already reduce the batch size to 8 and also reduce the epoch to 1 as mentioned above ,but it still does not work and time out on google colab so if possible please make video of only executing  this command which also contain output. 
python NBFNet/script/visualize.py -c NBFNet/config/knowledge_graph/fb15k237_visualize.yaml

no explanation is need in video just 1-2 minute video of executing this file. it is urgent if u understand.
and please send me pth file for 20 th epoch and  also other epoches if u have. so i can proceed on my own.
